Update README.md
rust-cli/confy pull request #77
Opened 2023-02-06 14:20 UTC by RampedIndent

Updated README.md to address #61

2023-02-06 17:14 UTC, matthiasbeyer requested changes

2023-02-06 17:14 UTC, matthiasbeyer commented on README.md
> +serde = { version = "1.0.152", features = ["derive"] } # <- Only one serde version needed (serde or serd_derive)
```suggestion
serde = { version = "1.0.152", features = ["derive"] } # <- Only one serde version needed (serde or serde_derive)
```

2023-02-06 17:14 UTC, matthiasbeyer commented on README.md
> +serde_derive = "1.0.152" # <- Only one serde version needed (serde or serd_derive)
```suggestion
serde_derive = "1.0.152" # <- Only one serde version needed (serde or serde_derive)
```

2023-02-09 19:43 UTC, deg4uss3r commented
Merging/rebasing `main` will fix CI but this does not touch `src/lib.rs` so it is not necessary.

2023-02-16 09:06 UTC, closed without merging

2023-02-16 09:07 UTC, RampedIndent commented
New pull request for issue #80